export const BASE_COLOR = {
  primaryColor: '#ff6f00',
  darkPrimaryColor: '#C31C0D',
  lightPrimaryColor: '#FF8A65',
  accentColor: '#4A90A4',
  textPrimaryColor: '#212121',
  textSecondaryColor: '#E0E0E1',
  grayColor: '#9B9B9B',
  darkBlueColor: '#24253D',
  dividerColor: '#BDBDBD',
  whiteColor: '#FFFFFF',
  fieldColor: '#F5F5F5',
  yellowColor: '#FDC60A',
  navyBlue: '#3C5A99',
  white: 'white',
};
