export const END_POINTS = {
  LOGIN: '/login',
  FORGOT: '/forgot',
  GET_TOKEN: '/token',
  CURRENT_LOGIN: '/login/CurrentLoginInfo',
  COUNTRIES: '/home/countries',
  JOB_POST: '/job/post',
  CHECK_INSTANT_BOOKING_AVAILABILITY:
    '/InstantBooking/CheckInstantBookingAvailability',
  AGENT_TEST: '/job/agenttest',
  CATEGORY_INFO: '/Question/CategoryInfo/457',
  GET_PROFILE_NOTIFICATIONS: '/profile/getprofilenotifications',
  GET_CUSTOMER_EDIT_DATA: '/customer/getcustomereditdata',
  QUESTIONS_WITH_OPTIONS: '/question/questionswithoptions/457',
  CUSTOMER_CREDIT_AVAILABILITY: '/loyalty/CustomerCreditAvailability',
  JOB_DESCRIPTION: '/Category/JobDescription',
  JOB_COMPLETE_UPSELL: '/category/JobCompleteUpsell/457',
  GET_PROMOTION_CATEGORIES: '/category/GetPromotionCategories',
  GETRATINGS_BY_PAGE: '/usta/getratingsbypage/1',
  MY_JOBS_BY_PAGE_USTA: '/ustajobs/myjobsbypage/2',
  GET_FEATURED_CATEGORIES: '/category/GetFeaturedCategories',
  SIGNUP: '/login/signup',
  GET_LOYALTY_POINTS: '/loyalty/CustomerCreditAvailability',
  GET_TOKEN_APPLE: '/token',
  DELETE_CARD: '/payment/deletecard?id={{cc_id}}',
  CREATE_CARD: '/payment/CreateCard',
  SET_AS_DEFAULT_CC: '/payment/SetAsDefault?Id={{cc_id}}',
  LIST_CARD: '/payment/listcard',
  PRE_CHECKOUT: '/checkout/precheckout',
  CHECKOUT_REQUEST: '/checkout/CheckoutRequest?id=434378176443',
  CHECKOUT_LIST: '/checkout/CheckoutList',
  COMPLETE_JOB_POST: '/CompleteJobPost?id=431844073862',
  COMPLETE_PAYMENT: '/Payment/Complete',
  GET_FINAL_COST: '/customerJobs/JobCloseFinalCost?id=485502043446&amount=3500',
  DASHBOARD: '/customer/dashboard',
  GET_TOKEN_2: '/token',
  REDEEM_LOYALTY: '/loyalty/Redeem?id=532660942829',
  CANCEL_LOYALTY: '/loyalty/Cancel?id=530575742332',
};
